{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "okp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "okp.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "okp.fullname" . }}
  port:
    targetPort: httpd
  tls:
    termination: {{ .Values.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
{{- end }}
