apiVersion: v1
kind: Service
metadata:
  name: {{ include "okp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "okp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 8080
    targetPort: 8080
    name: httpd
  - port: 8983
    targetPort: 8983
    name: solr
  selector:
    {{- include "okp.selectorLabels" . | nindent 4 }}
